Secret/Controllers/HomeController.cs
using FServices.Services.Interfaces;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Localization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using Models;
using Secret.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Secret.Controllers
{
    public class HomeController: Controller
    {
        IForumService _forumService;
        ILogger<HomeController> _logger;

        public HomeController(IForumService forumService, ILogger<HomeController> logger)
        {
            _forumService = forumService;
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public async Task<ActionResult> Sections()
        {
            List<Section> sections = await _forumService.GetSections();
            return PartialView("_Sections", sections); ;
        }

        public async Task<IActionResult> TopicDetail(int id)
        {
            Topic topic = await _forumService.GetTopic(id);
            return View(topic);
        }

        [HttpPost]
        public IActionResult SetLanguage(string culture, string returnUrl)
        {
            Response.Cookies.Append(
                CookieRequestCultureProvider.DefaultCookieName,
                CookieRequestCultureProvider.MakeCookieValue(new RequestCulture(culture)),
                new CookieOptions { Expires = DateTimeOffset.UtcNow.AddYears(1) }
            );

            return LocalRedirect(returnUrl);
        }

        public async Task<IActionResult> TopicMessages(int topicId, int page = 1)
        {
            int pageSize = 5;
            var topic = await _forumService.GetTopic(topicId);
            List<TopicMessage> source = await _forumService.GetTopicMessages(topicId);
            var count = source.Count();
            var items = source.Skip((page - 1) * pageSize).Take(pageSize).ToList();

            TopicMessagesViewModel pageViewModel = new TopicMessagesViewModel(count, page, pageSize);
            IndexTopicMessagesViewModel viewModel = new IndexTopicMessagesViewModel
            {
                PageViewModel = pageViewModel,
                TopicMessages = items,
                Topic = topic
            };

            return View("TopicDetail", viewModel);
        }
    }
}

Secret/Controllers/SectionsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using DBRepository;
using Models;
using Microsoft.AspNetCore.Authorization;
using FServices.Services.Interfaces;

namespace Secret.Controllers
{
    [Authorize(Roles = "admin")]
    public class SectionsController : Controller
    {
        private readonly RepositoryContext _context;
        private readonly IForumService _forumService;

        public SectionsController(IForumService forumService, RepositoryContext context)
        {
            _context = context;
            _forumService = forumService;
        }

        public async Task<IActionResult> Index()
        {
            return View(await _context.Sections.ToListAsync());
        }
    
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var section = await _context.Sections
                .FirstOrDefaultAsync(m => m.Id == id);
            if (section == null)
            {
                return NotFound();
            }

            return View(section);
        }

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Name")] Section section)
        {
            if (ModelState.IsValid)
            {
                await _forumService.AddSection(section);
                return RedirectToAction(nameof(Index));
            }
            return View(section);
        }

        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var section = await _context.Sections.FindAsync(id);
            if (section == null)
            {
                return NotFound();
            }
            return View(section);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Name")] Section section)
        {
            if (id != section.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(section);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!SectionExists(section.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(section);
        }

        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var section = await _context.Sections
                .FirstOrDefaultAsync(m => m.Id == id);
            if (section == null)
            {
                return NotFound();
            }

            return View(section);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            await _forumService.DeleteSection(id);
            return RedirectToAction(nameof(Index));
        }

        private bool SectionExists(int id)
        {
            return _context.Sections.Any(e => e.Id == id);
        }
    }
}

Secret/Controllers/TopicsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using DBRepository;
using Models;
using Microsoft.AspNetCore.Authorization;
using DBRepository.Interfaces;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.SignalR;
using Secret.Hubs;

namespace Secret.Controllers
{
    [Authorize]
    public class TopicsController : Controller
    {
        private readonly RepositoryContext _context;
        private readonly IForumRepository _forumRepository;
        private readonly UserManager<User> _userManager;
        IHubContext<NotificationHub> notificationHub;

        public TopicsController(IHubContext<NotificationHub> notificationHub, UserManager<User> userManager, IForumRepository forumRepository, RepositoryContext context)
        {
            _userManager = userManager;
            _forumRepository = forumRepository;
            _context = context;
            this.notificationHub = notificationHub;
        }

        public async Task<IActionResult> Index()
        {
            var repositoryContext = _context.Topics.Include(t => t.Author).Include(t => t.Section);
            return View(await repositoryContext.ToListAsync());
        }

        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var topic = await _context.Topics
                .Include(t => t.Author)
                .Include(t => t.Section)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (topic == null)
            {
                return NotFound();
            }

            return View(topic);
        }

        public IActionResult Create(int id)
        {
            ViewData["SectionId"] = id;
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Name, SectionId")] Topic topic)
        {
            User currentUser = await _userManager.GetUserAsync(HttpContext.User);

            topic.AuthorId = currentUser.Id;

            if (ModelState.IsValid)
            {
                await _forumRepository.AddTopic(topic);

                return RedirectToAction("Index", "Home");
            }
          
            return RedirectToAction("Index", "Home");
        }

        [Authorize(Roles = ("admin"))]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                await notificationHub.Clients.All.SendAsync("Send", "Bad Request");
                return BadRequest();
            }

            var topic = await _context.Topics.FindAsync(id);
            if (topic == null)
            {
                await notificationHub.Clients.All.SendAsync("Send", "Could not find topic");
                return NotFound();
            }
            ViewData["AuthorId"] = new SelectList(_context.Users, "Id", "Id", topic.AuthorId);
            ViewData["SectionId"] = new SelectList(_context.Sections, "Id", "Id", topic.SectionId);
            return View(topic);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Name,AuthorId,SectionId")] Topic topic)
        {
            if (id != topic.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(topic);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!TopicExists(topic.Id))
                    {
                        await notificationHub.Clients.All.SendAsync("Send", "Could not find topic");
                        return NotFound();
                    }
                    else
                    {
                        await notificationHub.Clients.All.SendAsync("Send", "Topic was already changed");
                        return BadRequest();
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["AuthorId"] = new SelectList(_context.Users, "Id", "Id", topic.AuthorId);
            ViewData["SectionId"] = new SelectList(_context.Sections, "Id", "Id", topic.SectionId);
            return View(topic);
        }

        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                await notificationHub.Clients.All.SendAsync("Send", "Bad Request");
                return BadRequest();
            }

            var topic = await _context.Topics
                .Include(t => t.Author)
                .Include(t => t.Section)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (topic == null)
            {
                await notificationHub.Clients.All.SendAsync("Send", "Could not find topic");
                return NotFound();
            }

            return View(topic);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var topic = await _context.Topics.FindAsync(id);
            _context.Topics.Remove(topic);
            await _context.SaveChangesAsync();
            return RedirectToAction("Details", "Sections", new { id = topic.SectionId });
        }

        private bool TopicExists(int id)
        {
            return _context.Topics.Any(e => e.Id == id);
        }
    }
}

Secret/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Index";
    Layout = "__Layout";
}

<div class="container-fluid">
    @{await Html.RenderPartialAsync("_Sections");}
</div>

Secret/Views/Home/TopicDetail.cshtml
@using Secret.ViewModels;
@model IndexTopicMessagesViewModel;
@using Microsoft.AspNetCore.Mvc.Localization
@inject IViewLocalizer Localizer

@{
    ViewData["Title"] = "c4";
    Layout = "__Layout";
}
<div class="container-fluid mt-3 card">
    <div class="card-body">
        <div><span class="fas fa-directions fa-lg"></span> @Model.Topic.Name</div>
        <ul class="mt-3 list-group">
            @foreach (Models.TopicMessage item in Model.TopicMessages)
            {
                <li class="list-group-item">
                    <div>
                        <span class="fas fa-comment"></span>
                        <span>@item.Author.UserName</span> <div><div class="user-comment">@item.Message</div></div>
                        <user>
                            <a onclick="invoke(this);" message-id=@item.Id><div class="fas fa-heart"></div></a><span class="@item.Id ml-1">@item.Likes.Count()</span>
                        </user>
                    </div>
                    <admin class="float-right">
                        <a class="btn btn-outline-info" asp-action="Delete" asp-controller="TopicMessages" asp-route-id="@item.Id"><span class="fas fa-minus fa-lg"></span>@Localizer["Delete"]</a>
                    </admin>
                </li>
            }

        </ul>
        <a class="btn btn-outline-info mt-3" asp-action="Create" asp-controller="TopicMessages" asp-route-id="@Model.Topic.Id"><span class="fas fa-plus fa-lg"></span>@Localizer["AddMessage"]</a>
        <page-link class="mt-3" topic-id=@Model.Topic.Id page-model="Model.PageViewModel" page-action="TopicMessages"></page-link>
    </div>
</div>

Secret/Views/Home/_DetailSection.cshtml
@model Models.Section
@inject FServices.Services.Interfaces.IForumService ForumService;
@using Microsoft.AspNetCore.Mvc.Localization
@inject IViewLocalizer Localizer
<div>
    <p><span class="fas fa-directions fa-lg"></span> @Model.Name</p>

    @if (User.Identity.IsAuthenticated)
    {
        <p class="mt-3">
            <a class="btn btn-outline-info" asp-controller="Topics" asp-action="Create/@{@Model.Id}"><span class="fas fa-plus fa-lg"></span>@Localizer["NewTopic"]</a>
        </p>
    }

    <ul class="list-group">
        @{await Html.RenderPartialAsync("_Topics", Model.Topics);}
    </ul>

</div>

Secret/Views/Home/_Sections.cshtml
@using FServices.Services.Interfaces;
@inject IForumService ForumService
<ul class="list-group">
    @{
        var services = await ForumService.GetSections();

        @foreach (Models.Section s in services)
        {
    <li class="list-group-item">@{await Html.RenderPartialAsync("_DetailSection", s);}</li>
        }
    }
</ul>

Secret/Views/Home/_Topics.cshtml
@model IEnumerable<Models.Topic>
@using Microsoft.AspNetCore.Mvc.Localization
@inject IViewLocalizer Localizer
@foreach (Models.Topic t in Model)
{
    <li class="list-group-item">
        <a asp-action="TopicMessages" asp-route-topicId="@t.Id"><span class="fas fa-database fa-ms"></span> @t.Name</a>
        <admin class="float-right">
            <a asp-controller="Topics" asp-action="Delete" asp-route-id="@t.Id" class="btn btn-outline-info"><span class="fas fa-minus fa-lg"></span>@Localizer["Delete"]</a>
        </admin>
    </li>
}