Secret/Controllers/RolesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Models;
using Secret.ViewModels;

namespace Secret.Controllers
{
    [Authorize(Roles = "admin")]
    public class RolesController : Controller
    {
        RoleManager<IdentityRole> _roleManager;
        UserManager<User> _userManager;
        public RolesController(RoleManager<IdentityRole> roleManager, UserManager<User> userManager)
        {
            _roleManager = roleManager;
            _userManager = userManager;
        }
        public IActionResult Index() => View(_roleManager.Roles.ToList());

        public IActionResult Create() => View();
        [HttpPost]
        public async Task<IActionResult> Create(string name)
        {
            if (!string.IsNullOrEmpty(name))
            {
                IdentityResult result = await _roleManager.CreateAsync(new IdentityRole(name));
                if (result.Succeeded)
                {
                    return RedirectToAction("Index");
                }
                else
                {
                    foreach (var error in result.Errors)
                    {
                        ModelState.AddModelError(string.Empty, error.Description);
                    }
                }
            }
            return View(name);
        }

        [HttpPost]
        public async Task<IActionResult> Delete(string id)
        {
            IdentityRole role = await _roleManager.FindByIdAsync(id);
            if (role != null)
            {
                IdentityResult result = await _roleManager.DeleteAsync(role);
            }
            return RedirectToAction("Index");
        }

        public IActionResult UserList() => View(_userManager.Users.ToList());

        public async Task<IActionResult> Edit(string userId)
        {
            User user = await _userManager.FindByIdAsync(userId);
            if (user != null)
            {
                var userRoles = await _userManager.GetRolesAsync(user);
                var allRoles = _roleManager.Roles.ToList();
                ChangeRoleViewModel model = new ChangeRoleViewModel
                {
                    UserId = user.Id,
                    UserEmail = user.Email,
                    UserRoles = userRoles,
                    AllRoles = allRoles
                };
                return View(model);
            }

            return NotFound();
        }

        [HttpPost]
        public async Task<IActionResult> Edit(string userId, List<string> roles)
        {
            User user = await _userManager.FindByIdAsync(userId);
            if (user != null)
            {
                var userRoles = await _userManager.GetRolesAsync(user);

                var allRoles = _roleManager.Roles.ToList();

                var addedRoles = roles.Except(userRoles);

                var removedRoles = userRoles.Except(roles);

                await _userManager.AddToRolesAsync(user, addedRoles);

                await _userManager.RemoveFromRolesAsync(user, removedRoles);

                return RedirectToAction("UserList");
            }

            return NotFound();
        }
    }
}

Secret/Controllers/SectionsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using DBRepository;
using Models;
using Microsoft.AspNetCore.Authorization;
using FServices.Services.Interfaces;

namespace Secret.Controllers
{
    [Authorize(Roles = "admin")]
    public class SectionsController : Controller
    {
        private readonly RepositoryContext _context;
        private readonly IForumService _forumService;

        public SectionsController(IForumService forumService, RepositoryContext context)
        {
            _context = context;
            _forumService = forumService;
        }

        public async Task<IActionResult> Index()
        {
            return View(await _context.Sections.ToListAsync());
        }
    
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var section = await _context.Sections
                .FirstOrDefaultAsync(m => m.Id == id);
            if (section == null)
            {
                return NotFound();
            }

            return View(section);
        }

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Name")] Section section)
        {
            if (ModelState.IsValid)
            {
                await _forumService.AddSection(section);
                return RedirectToAction(nameof(Index));
            }
            return View(section);
        }

        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var section = await _context.Sections.FindAsync(id);
            if (section == null)
            {
                return NotFound();
            }
            return View(section);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Name")] Section section)
        {
            if (id != section.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(section);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!SectionExists(section.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(section);
        }

        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var section = await _context.Sections
                .FirstOrDefaultAsync(m => m.Id == id);
            if (section == null)
            {
                return NotFound();
            }

            return View(section);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            await _forumService.DeleteSection(id);
            return RedirectToAction(nameof(Index));
        }

        private bool SectionExists(int id)
        {
            return _context.Sections.Any(e => e.Id == id);
        }
    }
}

Secret/Controllers/UsersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using FServices.Services.Interfaces;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Models;
using Secret.ViewModels;

namespace Secret.Controllers
{
    [Authorize]
    public class UsersController : Controller
    {
        UserManager<User> _userManager;
        IForumService _forumService;
        private readonly IHttpContextAccessor httpContextAccessor;

        public UsersController(IForumService forumService, UserManager<User> userManager, IHttpContextAccessor httpContextAccessor)
        {
            _userManager = userManager;
            _forumService = forumService;
            this.httpContextAccessor = httpContextAccessor;
        }

        public IActionResult Index() => View(_userManager.Users.ToList());

        [Authorize(Roles = "admin")]
        public IActionResult Create() => View();

        [HttpPost]
        [Authorize(Roles = "admin")]
        public async Task<IActionResult> Create(CreateUserViewModel model)
        {
            if (ModelState.IsValid)
            {
                User user = new User { Email = model.Email, UserName = model.Email };
                var result = await _userManager.CreateAsync(user, model.Password);
                if (result.Succeeded)
                {
                    return RedirectToAction("Index");
                }
                else
                {
                    foreach (var error in result.Errors)
                    {
                        ModelState.AddModelError(string.Empty, error.Description);
                    }
                }
            }
            return View(model);
        }

        [Authorize(Roles = "admin")]
        public async Task<IActionResult> Edit(string id)
        {
            User user = await _userManager.FindByIdAsync(id);
            if (user == null)
            {
                return NotFound();
            }
            EditUserViewModel model = new EditUserViewModel { Id = user.Id, Email = user.Email};
            return View(model);
        }

        [HttpPost]
        [Authorize(Roles = "admin")]
        public async Task<IActionResult> Edit(EditUserViewModel model)
        {
            if (ModelState.IsValid)
            {
                User user = await _userManager.FindByIdAsync(model.Id);
                if (user != null)
                {
                    user.Email = model.Email;
                    user.UserName = model.Email;

                    var result = await _userManager.UpdateAsync(user);
                    if (result.Succeeded)
                    {
                        return RedirectToAction("Index");
                    }
                    else
                    {
                        foreach (var error in result.Errors)
                        {
                            ModelState.AddModelError(string.Empty, error.Description);
                        }
                    }
                }
            }
            return View(model);
        }

        [HttpPost]
        [Authorize(Roles = "admin")]
        public async Task<ActionResult> Delete(string id)
        {
            User user = await _userManager.FindByIdAsync(id);
            if (user != null)
            {
                IdentityResult result = await _userManager.DeleteAsync(user);
            }
            return RedirectToAction("Index");
        }

        public async Task StartConversation(string id)
        {
            var currentUser = await _userManager.GetUserAsync(httpContextAccessor.HttpContext.User);
            var toUser = await _userManager.FindByIdAsync(id);
            if (toUser != null)
            {
                Conversation conversation = new Conversation();
                await _forumService.AddConverstation(conversation);
                UserConversation userConversation = new UserConversation()
                {
                    UserId = currentUser.Id,
                    ConversationId = conversation.Id
                };

                UserConversation userConversation2 = new UserConversation()
                {
                    UserId = toUser.Id,
                    ConversationId = conversation.Id
                };

                await _forumService.AddUserConverstation(userConversation);
                await _forumService.AddUserConverstation(userConversation2);
            }
        }
    }
}

Secret/ViewComponents/UsersStatViewComponent.cs
using Microsoft.AspNetCore.Html;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.ViewComponents;
using Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Secret.ViewComponents
{
    public class UsersStatViewComponent : ViewComponent
    {
        private UserManager<User> _userManager;

        public UsersStatViewComponent(UserManager<User> userManager)
        {
            _userManager = userManager;
        }

        public async Task<IViewComponentResult> InvokeAsync()
        {
            var usersCount = _userManager.Users.Count();
            var admins = await _userManager.GetUsersInRoleAsync("admin");
            var adminsCount = admins.Count();

            return new HtmlContentViewComponentResult(
                new HtmlString($"<p class=\"text-secondary\">Users: {usersCount}</p> <p class=\"text-secondary\">Admins: {adminsCount}</p>")); ;
        }
    }
}

Secret/Views/Shared/_Admin.cshtml
@using Microsoft.AspNetCore.Mvc.Localization
@inject IViewLocalizer Localizer

<div>

@await Component.InvokeAsync("SectionsStat")
@await Component.InvokeAsync("UsersStat")
<span class="text-secondary">@Localizer["Language"]: @Localizer["Header"]</span>

</div>

Secret/Views/Shared/_SelectLanguage.cshtml
@using Microsoft.AspNetCore.Builder
@using Microsoft.AspNetCore.Http.Features
@using Microsoft.AspNetCore.Localization
@using Microsoft.AspNetCore.Mvc.Localization
@using Microsoft.Extensions.Options

@inject IViewLocalizer Localizer
@inject IOptions<RequestLocalizationOptions> LocOptions

@{
    var requestCulture = Context.Features.Get<IRequestCultureFeature>();
    var cultureItems = LocOptions.Value.SupportedUICultures
        .Select(c => new SelectListItem { Value = c.Name, Text = c.DisplayName })
        .ToList();
}
<div class="nav-item form-group float-left" style="width: 25%">
    <form asp-controller="Home" asp-action="SetLanguage"
          asp-route-returnUrl="@Context.Request.Path"
          method="post" class="float-left">
        <select class="form-control" style="{ width: 100px;}" name="culture" onchange="this.form.submit();"
                asp-for="@requestCulture.RequestCulture.UICulture.Name"
                asp-items="cultureItems"></select>
    </form>

</div>

Secret/Views/Shared/__Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"]</title>
    <environment include="Development">
        <link rel="stylesheet" href="~/lib/css/bootstrap.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="~/lib/css/bootstrap.min.css" />
    </environment>
    <link rel="stylesheet" href="~/css/main.css" />
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.4.1/css/all.css" integrity="sha384-5sAR7xN1Nv6T6+dT2mhtzEpVJvfS3NScPQTrOxhwjIuvcA67KV2R5Jz6kr4abQsz" crossorigin="anonymous">
</head>
<body>
    <!--меню-->
    <nav class="navbar navbar-dark bg-dark">
        <span class="fab fa-angellist fa-3x"></span>
        <a class="navbar-brand" asp-controller="Home" asp-action="Index">Secret</a>
        @if (User.Identity.IsAuthenticated)
        {
        <div class="col-8">
            <div class="nav-item float-left">
                <a class="nav-link text-info" asp-controller="Users">Users</a>
            </div>
            <user>
                <div class="nav-item float-left">
                    <a class="nav-link text-info" asp-controller="Conversation">Conversations</a>
                </div>
            </user>
            <admin>
                <div class="nav-item float-left">
                    <a class="nav-link text-info" asp-controller="Roles">Roles</a>
                </div>
                <div class="nav-item float-left">
                    <a class="nav-link text-info" asp-controller="Sections">Sections</a>
                </div>
            </admin>
        </div>
            <div class="col-2 btn-group">
                <button type="button" class="btn btn-outline-primary dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    @User.Identity.Name
                </button>
                <div class="dropdown-menu">
                    <form method="post" asp-controller="Account" asp-action="LogOff">
                        <input class="dropdown-item" type="submit" value="Log Out" />
                    </form>
                </div>
            </div>

            <!--           <form asp-action="Delete" asp-route-id="." method="post">
                <a class="btn btn-sm btn-primary" asp-action="Edit" asp-route-id=".">Изменить</a>
                <a class="btn btn-sm btn-primary" asp-action="ChangePassword" asp-route-id=".">Сменить пароль</a>
                <button type="submit" class="btn btn-sm btn-danger">
                    Удалить
                </button>
            </form>-->
        }
        else
        {
            <div class="col-2">
                <form method="post" asp-controller="Account" asp-action="Login" class="mr-1 float-left form-inline">
                    <input class="btn btn-outline-secondary" type="submit" value="Login" />
                </form>
                <form method="post" asp-controller="Account" asp-action="Register" class="form-inline">
                    <input class="btn btn-outline-info" type="submit" value="Sign Up" />
                </form>
            </div>
        }
    </nav>
    <!--основной контент-->
    <div class="container body-content">
        <div id="chatroom" style="overflow:scroll; height:200px;"></div>
        <div id="inputForm" class="mb-3 mt-3">
            <user>
                <input type="text" placeholder="Message..." id="message" />
                <input type="button" class="btn btn-outline-info ml-3" id="sendBtn" value="Send" />
            </user>
        </div>
    </div>
        @RenderBody()
        <hr />
        <admin class="mt-3">
            @{await Html.RenderPartialAsync("_Admin");}
        </admin>
        <hr />
        @await Html.PartialAsync("_SelectLanguage")
        <footer></footer>
    </div>
    <environment include="Development">
        <script src="~/lib/js/jquery.js"></script>
        <script src="~/lib/js/bootstrap.bundle.js"></script>
    </environment>
    <environment exclude="Development">
        <script src="~/lib/js/jquery.min.js"></script>
        <script src="~/lib/js/bootstrap.bundle.min.js"></script>
    </environment>
    <script src="~/lib/js/signalr.min.js"></script>
    <script src="~/js/main.js"></script>
</body>
</html>